## Creating a Pandas Series with a List

In [1]:
import pandas as pd

In [2]:
pd.Series([10, 20, 30, 40, 50])

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [3]:
list_data = [2, 4, 6, 8, 10]
list_index = ["a", "b", "c", "d", "e"]

In [4]:
variable = pd.Series(data = list_data, index = list_index, dtype = "float")

In [5]:
variable

a     2.0
b     4.0
c     6.0
d     8.0
e    10.0
dtype: float64

In [6]:
type(variable)

pandas.core.series.Series

In [9]:
list_data = [2, 4, 6, 8, 10, 12]
list_index = ["a", "b", "c", "d", "e"]

In [10]:
variable = pd.Series(data = list_data, index = list_index, dtype = "float")

ValueError: Length of passed values is 6, index implies 5.

## Creating a Pandas Series with a Dictionary

In [11]:
import pandas as pd 

In [12]:
dictionary = {"ferrari" : 334.7, "porche" : 337.9, "lamborghini" : 349}

In [13]:
pd.Series(data = dictionary)

ferrari        334.7
porche         337.9
lamborghini    349.0
dtype: float64

In [14]:
variable = pd.Series(data = dictionary, index = ["porche", "bugatti", "ferrari"])

In [15]:
variable

porche     337.9
bugatti      NaN
ferrari    334.7
dtype: float64

## Creating Pandas Series with NumPy Array

In [16]:
import numpy as np
import pandas as pd

In [17]:
example = np.array([1, 3.3, 5, 7.2, 9])
labels = np.array(["a", "b", "c", "d", "e"])

In [18]:
variable = pd.Series(data = example, index = labels)

In [19]:
variable

a    1.0
b    3.3
c    5.0
d    7.2
e    9.0
dtype: float64

## Object Types in Series

In [20]:
import pandas as pd

In [21]:
pd.Series(["world", 100, 5.8, False])

0    world
1      100
2      5.8
3    False
dtype: object

In [22]:
example = pd.Series(["world", 100, 5.8, False])

In [23]:
example[0]

'world'

In [24]:
print(type(example[0]))

<class 'str'>


In [25]:
print(type(example[1]))
print(type(example[2]))
print(type(example[3]))

<class 'int'>
<class 'float'>
<class 'bool'>


In [26]:
pd.Series([sum, type, max])

0    <built-in function sum>
1             <class 'type'>
2    <built-in function max>
dtype: object

## Examining the Primary Features of the Pandas Series  

In [27]:
import pandas as pd

In [28]:
example = pd.Series([10, 20, 30, 40, 50, 60, 70])

In [29]:
example

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [30]:
example.axes

[RangeIndex(start=0, stop=7, step=1)]

In [31]:
example.dtype

dtype('int64')

In [32]:
example.size

7

In [33]:
example.ndim

1

In [34]:
example.head()

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [35]:
example.tail()

2    30
3    40
4    50
5    60
6    70
dtype: int64

## Most Applied Methods on Pandas Series

In [36]:
import pandas as pd

In [37]:
variable = pd.Series([8, 3, 6, 5, 1], index = ["b", "d", "c", "a", "e"])

In [38]:
variable

b    8
d    3
c    6
a    5
e    1
dtype: int64

In [39]:
new_variable = variable.sort_index()

In [40]:
new_variable

a    5
b    8
c    6
d    3
e    1
dtype: int64

In [41]:
new_variable2 = variable.sort_values()

In [42]:
new_variable2

e    1
d    3
a    5
c    6
b    8
dtype: int64

In [43]:
variable

b    8
d    3
c    6
a    5
e    1
dtype: int64

In [44]:
variable.isin([6, 1])

b    False
d    False
c     True
a    False
e     True
dtype: bool

In [45]:
variable[variable.isin([6, 1])]

c    6
e    1
dtype: int64

In [46]:
variable.values

array([8, 3, 6, 5, 1], dtype=int64)

In [47]:
[i for i in variable.values]

[8, 3, 6, 5, 1]

In [48]:
variable.index

Index(['b', 'd', 'c', 'a', 'e'], dtype='object')

In [49]:
[i for i in variable.index]

['b', 'd', 'c', 'a', 'e']

In [50]:
variable.items

<bound method Series.items of b    8
d    3
c    6
a    5
e    1
dtype: int64>

In [51]:
variable.items()

In [52]:
list(variable.items())

[('b', 8), ('d', 3), ('c', 6), ('a', 5), ('e', 1)]

In [53]:
for index, value in variable.items():
    print(index, "-", value)

b - 8
d - 3
c - 6
a - 5
e - 1


## Indexing and Slicing Pandas Series

In [54]:
import pandas as pd

In [55]:
example = pd.Series(["+90", "+49", "+33", "+39", "+46", "+47"], index = ["Turkey", "Germany", "France", "Italy", "Sweden", "Norway"])

In [56]:
example

Turkey     +90
Germany    +49
France     +33
Italy      +39
Sweden     +46
Norway     +47
dtype: object

In [57]:
example["Germany"]

'+49'

In [58]:
example[1]

'+49'

In [59]:
example["France":"Sweden"]

France    +33
Italy     +39
Sweden    +46
dtype: object

In [60]:
example[2:5]

France    +33
Italy     +39
Sweden    +46
dtype: object

In [61]:
example[2:5:2]

France    +33
Sweden    +46
dtype: object

In [62]:
example[["Norway", "Turkey"]]

Norway    +47
Turkey    +90
dtype: object

## Creating Pandas DataFrame with List

In [63]:
import pandas as pd

In [64]:
list_example = [5, 10, 15, 20, 25]

In [65]:
list_example

[5, 10, 15, 20, 25]

In [66]:
pd.DataFrame(data = list_example, columns = ["values"], dtype = "float" )

values
0     5.0
1    10.0
2    15.0
3    20.0
4    25.0

## Creating Pandas DataFrame with NumPy Array

In [67]:
import numpy as np
import pandas as pd

In [68]:
array_example = np.random.randint(0, 50, (4, 4))

In [69]:
array_example

array([[17, 22, 14, 25],
       [ 5,  6,  3, 21],
       [40, 18, 34, 27],
       [ 4, 42, 35, 35]])

In [70]:
df = pd.DataFrame(array_example, index = ["a", "b", "c", "d"], columns = ["val1", "val2", "val3", "val4"])

In [71]:
df

val1  val2  val3  val4
a    17    22    14    25
b     5     6     3    21
c    40    18    34    27
d     4    42    35    35

## Creating Pandas DataFrame with Dictionary

In [72]:
import numpy as np
import pandas as pd

In [73]:
x = np.random.randint(10, 50, size = 6)

In [74]:
x

array([49, 34, 40, 49, 28, 43])

In [75]:
y = np.random.randint(10, 50, size = 6)
z = np.random.randint(10, 50, size = 6)
t = np.random.randint(10, 50, size = 6)

In [76]:
dict_example = {"val1":x, "val2":y, "val3":z, "val4":t}

In [77]:
dict_example

{'val1': array([49, 34, 40, 49, 28, 43]),
 'val2': array([38, 11, 19, 28, 29, 11]),
 'val3': array([31, 12, 21, 23, 35, 47]),
 'val4': array([38, 42, 47, 35, 17, 17])}

In [78]:
df = pd.DataFrame(dict_example)

In [79]:
df

val1  val2  val3  val4
0    49    38    31    38
1    34    11    12    42
2    40    19    21    47
3    49    28    23    35
4    28    29    35    17
5    43    11    47    17

## Examining the Properties of Pandas DataFrames

In [80]:
import numpy as np
import pandas as pd

In [81]:
x = np.random.randint(10, 50, size = 6)
y = np.random.randint(10, 50, size = 6)
z = np.random.randint(10, 50, size = 6)
t = np.random.randint(10, 50, size = 6)

dict_example = {"val1":x, "val2":y, "val3":z, "val4":t}

df = pd.DataFrame(dict_example)

In [82]:
df

val1  val2  val3  val4
0    32    39    19    25
1    40    34    16    41
2    42    27    12    29
3    20    42    48    28
4    10    47    31    11
5    47    16    46    42

In [83]:
df.head()

val1  val2  val3  val4
0    32    39    19    25
1    40    34    16    41
2    42    27    12    29
3    20    42    48    28
4    10    47    31    11

In [84]:
df.head(3)

val1  val2  val3  val4
0    32    39    19    25
1    40    34    16    41
2    42    27    12    29

In [85]:
df.tail(3)

val1  val2  val3  val4
3    20    42    48    28
4    10    47    31    11
5    47    16    46    42

In [86]:
df.columns

Index(['val1', 'val2', 'val3', 'val4'], dtype='object')

In [87]:
[i for i in df.columns]

['val1', 'val2', 'val3', 'val4']

In [88]:
df

val1  val2  val3  val4
0    32    39    19    25
1    40    34    16    41
2    42    27    12    29
3    20    42    48    28
4    10    47    31    11
5    47    16    46    42

In [89]:
df.columns = ["new1", "new2", "new3", "new4"]

In [90]:
df

new1  new2  new3  new4
0    32    39    19    25
1    40    34    16    41
2    42    27    12    29
3    20    42    48    28
4    10    47    31    11
5    47    16    46    42

In [91]:
df.values

array([[32, 39, 19, 25],
       [40, 34, 16, 41],
       [42, 27, 12, 29],
       [20, 42, 48, 28],
       [10, 47, 31, 11],
       [47, 16, 46, 42]])

In [92]:
type(df.values)

numpy.ndarray

In [93]:
type(df)

pandas.core.frame.DataFrame

In [94]:
df.shape

(6, 4)

In [95]:
df.ndim

2

In [96]:
df.size

24

## Element Selection Operations in Pandas DataFrames: Lesson 1

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(101)
df = pd.DataFrame(data = np.random.randn(6,5), index = "A B C D E F".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [13]:
np.random.seed(101)
df = pd.DataFrame(data = np.random.randn(6,5), index = "A B C D E F".split(), columns = ["v1 v2 v3 v4 v5".split()])

In [14]:
df

v1        v2        v3        v4        v5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [15]:
df.v1

v1
A  2.706850
B -0.319318
C  0.528813
D  0.955057
E  0.302665
F  0.390528

In [3]:
df

VAL1      VAL2      VAL3      VAL4      VAL5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [4]:
df["VAL1"]

A    2.706850
B   -0.319318
C    0.528813
D    0.955057
E    0.302665
F    0.390528
Name: VAL1, dtype: float64

In [5]:
df.VAL1

A    2.706850
B   -0.319318
C    0.528813
D    0.955057
E    0.302665
F    0.390528
Name: VAL1, dtype: float64

In [102]:
df["VAL1"].values

array([ 2.70684984, -0.31931804,  0.52881349,  0.95505651,  0.30266545,
        0.39052784])

In [103]:
df[["VAL1"]]

VAL1
A  2.706850
B -0.319318
C  0.528813
D  0.955057
E  0.302665
F  0.390528

In [104]:
df[["VAL1"]]["B":"D"]

VAL1
B -0.319318
C  0.528813
D  0.955057

In [105]:
df[["VAL1"]][1:4]

VAL1
B -0.319318
C  0.528813
D  0.955057

## Element Selection Operations in Pandas DataFrames: Lesson 2

In [106]:
import numpy as np
import pandas as pd

In [107]:
np.random.seed(101)
df = pd.DataFrame(data = np.random.randn(6,5), index = "A B C D E F".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [108]:
df

VAL1      VAL2      VAL3      VAL4      VAL5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [109]:
df[["VAL2", "VAL5"]]

VAL2      VAL5
A  0.628133  0.651118
B -0.848077  0.740122
C -0.589001 -0.933237
D  0.190794  0.683509
E  1.693723 -0.134841
F  0.166905  0.072960

In [110]:
variable = ["VAL3", "VAL4"]

In [111]:
df[variable]

VAL3      VAL4
A  0.907969  0.503826
B  0.605965 -2.018168
C  0.188695 -0.758872
D  1.978757  2.605967
E -1.706086 -1.159119
F  0.184502  0.807706

In [112]:
df

VAL1      VAL2      VAL3      VAL4      VAL5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [113]:
df["B":"D"]

VAL1      VAL2      VAL3      VAL4      VAL5
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509

In [114]:
df[1:4]

VAL1      VAL2      VAL3      VAL4      VAL5
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509

In [115]:
df["E"]

KeyError: 'E'

In [116]:
df["E":"E"]

VAL1      VAL2      VAL3      VAL4      VAL5
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841

In [117]:
df["E":"E"][["VAL2","VAL5"]]

VAL2      VAL5
E  1.693723 -0.134841

## Top Level Element Selection in Pandas DataFrames: Structure of loc and iloc: Lesson 1

In [118]:
import numpy as np
import pandas as pd

In [119]:
np.random.seed(101)

array = np.random.randint(10, 50, (10, 5))
df = pd.DataFrame(data = array , index = "A B C D E F G H I J".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [120]:
df

VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [121]:
df.loc["A":"D"]

VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29

In [122]:
df.iloc[0:4]

VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29

In [123]:
df

VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [124]:
df.loc["C", "VAL4"]

39

In [125]:
df.iloc[2, 3]

39

## Top Level Element Selection in Pandas DataFrames: Structure of loc and iloc: Lesson 2

In [126]:
import numpy as np
import pandas as pd

In [127]:
np.random.seed(101)

array = np.random.randint(10, 50, (10, 5))
df = pd.DataFrame(data = array , index = "A B C D E F G H I J".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [128]:
df

VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [129]:
df.loc["C":"G","VAL3"]

C    22
D    44
E    41
F    46
G    20
Name: VAL3, dtype: int32

In [130]:
df.loc["C":"G",["VAL3"]]

VAL3
C    22
D    44
E    41
F    46
G    20

In [131]:
df.loc["C":"G"][["VAL3"]]

VAL3
C    22
D    44
E    41
F    46
G    20

In [132]:
df

VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [133]:
df.iloc[2:7,2]

C    22
D    44
E    41
F    46
G    20
Name: VAL3, dtype: int32

In [134]:
df.iloc[2:7,[2]]

VAL3
C    22
D    44
E    41
F    46
G    20

In [135]:
df.iloc[2:7][["VAL3"]]

VAL3
C    22
D    44
E    41
F    46
G    20

## Top Level Element Selection in Pandas DataFrames: Structure of loc and iloc: Lesson 3

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(101)

array = np.random.randint(10, 50, (10, 5))
df = pd.DataFrame(data = array , index = "A B C D E F G H I J".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [3]:
df

VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [4]:
df.loc["C":"H","VAL2":"VAL4"]

VAL2  VAL3  VAL4
C    15    22    39
D    39    44    18
E    22    41    33
F    18    46    29
G    17    20    49
H    28    17    49

In [140]:
df.iloc[2:8,1:4]

VAL2  VAL3  VAL4
C    15    22    39
D    39    44    18
E    22    41    33
F    18    46    29
G    17    20    49
H    28    17    49

In [141]:
df.iloc[2:8,1:4].loc["E":"F", ["VAL3"]]

VAL3
E    41
F    46

## Element Selection with Conditional Operations in Pandas Data Frames

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(101)

array = np.random.randint(10, 50, (10, 5))
df = pd.DataFrame(data = array , index = "A B C D E F G H I J".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [3]:
df

VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [4]:
df > 20

VAL1   VAL2   VAL3   VAL4   VAL5
A   True   True   True  False   True
B   True  False   True  False   True
C  False  False   True   True   True
D  False   True   True  False   True
E  False   True   True   True  False
F  False  False   True   True   True
G   True  False  False   True   True
H  False   True  False   True   True
I  False   True   True   True   True
J   True   True   True   True   True

In [5]:
df[df > 20]

VAL1  VAL2  VAL3  VAL4  VAL5
A  41.0  21.0  27.0   NaN  33.0
B  21.0   NaN  23.0   NaN  38.0
C   NaN   NaN  22.0  39.0  29.0
D   NaN  39.0  44.0   NaN  29.0
E   NaN  22.0  41.0  33.0   NaN
F   NaN   NaN  46.0  29.0  45.0
G  38.0   NaN   NaN  49.0  48.0
H   NaN  28.0   NaN  49.0  25.0
I   NaN  22.0  27.0  21.0  25.0
J  43.0  39.0  34.0  46.0  29.0

In [6]:
df["VAL1"] < 20

A    False
B    False
C     True
D     True
E    False
F     True
G    False
H     True
I     True
J    False
Name: VAL1, dtype: bool

In [7]:
df[df["VAL1"] < 20]

VAL1  VAL2  VAL3  VAL4  VAL5
C    10    15    22    39    29
D    18    39    44    18    29
F    19    18    46    29    45
H    19    28    17    49    25
I    10    22    27    21    25

In [10]:
df[df["VAL1"] < 20]["VAL2"]

C    15
D    39
F    18
H    28
I    22
Name: VAL2, dtype: int32

In [150]:
df[df["VAL1"] < 20][["VAL2"]]

VAL2
C    15
D    39
F    18
H    28
I    22

In [151]:
df[df["VAL1"] > 20][["VAL2", "VAL5"]]

VAL2  VAL5
A    21    33
B    19    38
G    17    48
J    39    29

In [152]:
df 

VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [153]:
df[(df["VAL1"] > 20) & (df["VAL4"] < 18)]

VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38

In [154]:
df[(df < 35) | (df["VAL5"] > 20)]

VAL1  VAL2  VAL3  VAL4  VAL5
A   NaN  21.0  27.0  16.0  33.0
B  21.0  19.0  23.0  14.0   NaN
C  10.0  15.0  22.0   NaN  29.0
D  18.0   NaN   NaN  18.0  29.0
E  20.0  22.0   NaN  33.0  10.0
F  19.0  18.0   NaN  29.0   NaN
G   NaN  17.0  20.0   NaN   NaN
H  19.0  28.0  17.0   NaN  25.0
I  10.0  22.0  27.0  21.0  25.0
J   NaN   NaN  34.0   NaN  29.0

In [155]:
df

VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [13]:
df.loc[df.VAL2 > 25, ["VAL2", "VAL3", "VAL5"]]

VAL2  VAL3  VAL5
D    39    44    29
H    28    17    25
J    39    34    29

## Adding Columns to Pandas Data Frames

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
x = np.arange(0, 28).reshape(7, 4)

In [ ]:
x

In [ ]:
df = pd.DataFrame(data = x, columns = ["VAL1", "VAL2", "VAL3", "VAL4"])

In [ ]:
df

In [ ]:
df["VAL1"] + df["VAL2"]

In [ ]:
df["VAL5"] = df["VAL1"] + df["VAL2"]

In [ ]:
df

In [ ]:
df["VAL6"] = df["VAL3"] * df["VAL4"]

In [ ]:
df

In [ ]:
np.arange(28, 35)

In [ ]:
df["VAL7"] = np.arange(28, 35)

In [ ]:
df

In [ ]:
df["VAL8"] = [35, 36, 37, 38, 39, 40, 41]

In [ ]:
df

In [ ]:
df["VAL9"] =[35, 36, 37, 38, 39, 40]

## Removing Rows and Columns from Pandas Data frames

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
x = np.arange(0, 28).reshape(7, 4)
df = pd.DataFrame(data = x, columns = ["VAL1", "VAL2", "VAL3", "VAL4"])

In [ ]:
df

In [ ]:
df.drop(["VAL3", "VAL4"], axis = 1)

In [ ]:
df

In [ ]:
df.drop(["VAL3", "VAL4"], axis = 1, inplace = True)

In [ ]:
df

In [ ]:
df

## Null Values in Pandas Dataframes

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({'VAL1':[2, 4, np.nan, 6, np.nan, 8, 10],
                   'VAL2':[123, np.nan, 456, np.nan, 789, 246, 357],
                   'VAL3':['France', 'Greece', 'USA', 'Japan', "Sweden", "Norway", "Turkey"]})

In [3]:
df

VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [4]:
df.isnull()

VAL1   VAL2   VAL3
0  False  False  False
1  False   True  False
2   True  False  False
3  False   True  False
4   True  False  False
5  False  False  False
6  False  False  False

In [5]:
df.isnull().sum()

VAL1    2
VAL2    2
VAL3    0
dtype: int64

In [6]:
len(df)

7

In [7]:
df.isnull().sum() / len(df) * 100

VAL1    28.571429
VAL2    28.571429
VAL3     0.000000
dtype: float64

In [8]:
df.notnull()

VAL1   VAL2  VAL3
0   True   True  True
1   True  False  True
2  False   True  True
3   True  False  True
4  False   True  True
5   True   True  True
6   True   True  True

In [9]:
df.notnull().sum()

VAL1    5
VAL2    5
VAL3    7
dtype: int64

In [10]:
df.notnull().sum().sum()

17

In [ ]:
df["VAL1"].notnull()

In [ ]:
df[df["VAL1"].notnull()]

In [ ]:
df

In [ ]:
df.isnull().any()

In [ ]:
df.isnull().any(axis = 1)

In [ ]:
condition = df.isnull().any(axis = 1)

In [ ]:
df[condition]

In [ ]:
df[~condition]

In [ ]:
df

In [ ]:
df.notnull().all()

In [ ]:
df.isnull().all(axis = 1)

## Dropping Null Values: Dropna() Function

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame({'VAL1':[2, 4, np.nan, 6, np.nan, 8, 10],
                   'VAL2':[123, np.nan, 456, np.nan, 789, 246, 357],
                   'VAL3':['France', 'Greece', 'USA', 'Japan', "Sweden", "Norway", "Turkey"]})

In [ ]:
df

In [ ]:
df.dropna()

In [ ]:
df

In [ ]:
df.dropna(axis = 1)

In [ ]:
df["VAL4"] = np.nan

In [ ]:
df

In [ ]:
df.dropna(how = "all")

In [ ]:
df.dropna(how = "all", axis = 1)

In [ ]:
df

In [ ]:
df.dropna(how = "all", axis = 1, inplace = True)

In [ ]:
df

## Filling Null Values: Fillna() Function

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame({'VAL1':[2, 4, np.nan, 6, np.nan, 8, 10],
                   'VAL2':[123, np.nan, 456, np.nan, 789, 246, 357],
                   'VAL3':['France', 'Greece', 'USA', 'Japan', "Sweden", "Norway", "Turkey"]})

In [ ]:
df

In [ ]:
df.fillna(100000)

In [ ]:
df

In [ ]:
df["VAL1"].fillna(100000)

In [ ]:
df

In [ ]:
df.mean()

In [ ]:
df.fillna(df.mean())

In [ ]:
df

In [ ]:
df.fillna({"VAL1":100000, "VAL2":200000})

In [ ]:
df["VAL1"].fillna(df["VAL2"].mean())

In [ ]:
df

In [ ]:
df["VAL3"][0::2]

In [ ]:
df["VAL3"][0::2] = np.nan

In [ ]:
df

In [ ]:
df["VAL3"].fillna("Turkey")

In [ ]:
df.fillna(method = "ffill")

In [ ]:
df.fillna(method = "pad")

In [ ]:
df.fillna(method = "bfill")

In [ ]:
df.fillna(method = "backfill")